### ISSUE TITLE
Add 'react-virtualized-auto-sizer' as dependency

### ISSUE THREAD

**Issue by narinluangrath** [pupudu/window-table#1]
Thanks @pupudu for the component!
Don't forget to add 'react-virtualized-auto-sizer' as a dependency. It's imported, but not in the package.json.

**Comment by pupudu** [comment]
Hi @narinluangrath 
Thank you for pointing that out. 
I was initially planning to make `react-virtualized-auto-sizer` and `react-window` peer dependencies. But on second thought, what you suggest makes more sense. Hence I made both `react-virtualized-auto-sizer` and `react-window` direct dependencies. 

This change is available in v0.0.15
