### ISSUE TITLE
react-window on a next js ssr

### ISSUE THREAD

**Issue by techandmedia** [pupudu/window-table#17]

**Comment by techandmedia** [comment]
Hi there, I am just trying out window-table on next js (ssr) environment. 

There's an error occured during load "Unexpected token export. C:\...\node_modules\lodash-es\lodash.js:10"
export {default as add } from './add.js'

Here is the sandbox repo [https://codesandbox.io/s/nextwindowtable-dr0vz](url)

Thank you

**Comment by pupudu** [comment]
Hi @techandmedia 
Thank you for creating the issue. And sorry that you had to face this issue. I will look into this asap

**Comment by pupudu** [comment]
Hi @techandmedia You can see the sandbox here working with the new bugfix version 0.6.4
https://codesandbox.io/s/nextwindowtable-q1lu4

**Comment by techandmedia** [comment]
Thank you, now it works!

But the first time load is quite slow, I try to reduce to just 1000 and it's still slow the first time. Can you advise please?

**Comment by techandmedia** [comment]
Just want to let you know that it works super fast now! Thank you, you've done a great job!

**Comment by pupudu** [comment]
@techandmedia Glad to hear faster now. I took one more step and made it even faster for SSR. Now I am using an example nextJs app locally to make sure the library works great on SSR. 
An example codesandbox here: https://yl96z.sse.codesandbox.io/
