### ISSUE TITLE
Should we support Event Handler in this library?

### ISSUE THREAD

**Issue by onesinus** [pupudu/window-table#20]
The table works well since i follow the documentation https://window-table.now.sh/

But for now i'm thinking to add some event handler in table's rows such as onClick handler

as far as i see the documentation i don't get the event handler, is that possible to add some event with this module?

Thanks in advance

**Comment by pupudu** [comment]
Hi @onesinus 
Thank you for creating this issue. Adding event handlers are supported even as of now, though it may not be very clear at first. A TL;DR is, you can do this by supplying custom components as Row, Column, etc. 

I will quickly add a new guide to explain how this can be done with minimal effort.

**Comment by pupudu** [comment]
@onesinus I've added a new comprehensive guide on how we can leverage the customizability of this library to add event listeners to the rows. 

Let me know if you need any other clarifications.

Thanks.

**Comment by pupudu** [comment]
Also, would appreciate it if you can star the repo to support our growth. Thanks!

**Comment by onesinus** [comment]
Oke i will see and try, My star exactly for you :)
