### ISSUE TITLE
Nested tables

### ISSUE THREAD

**Issue by OVBondHUB** [pupudu/window-table#25]
Hi, your package has some problems with nested tables. I try to render one table, but DOM has rendered three same tables :
<img width="1911" alt="Screenshot 2019-07-29 at 15 28 22" src="https://user-images.githubusercontent.com/45013125/62052928-d4c1b500-b216-11e9-844d-4c85307e999d.png">

**Comment by pupudu** [comment]
Hi @OVBondHUB 
Thank you for opening this issue. 

If I understand your concern correctly, you are referring to the three `<table>` tags you see in the dom. If that is the case, this is expected and that is exactly what's makes this library be able to render a virtualized table using table tags. 

Developers usually state that it is not possible to virtualize a table with tags such as `table`, `tr`, `td` etc. The author of react-window, react-virtualized and react-core team member Brian Vaughn also stated the same idea. 

They are not wrong. It is impossible to virtualize a table made of these tags. What we are doing instead, is rendering two tables, one for the table headings and one for the table body. The third table you see is used for measurements. This approach sounded interesting to Brian Vaughn himself. 

Thus I am quite confident that this is the correct thing to do. Happy to discuss. If you have any more questions, feel free to comment. 

Thanks

**Comment by OVBondHUB** [comment]
Hi, @pupudu, Thank you for explanation. I junior developer and I didn't know, that impossible to virtualize a table using standard tags. Thank you for your package

**Comment by pupudu** [comment]
No worries @OVBondHUB 
Since you are happy with the discussion, I will close this issue.
