### ISSUE TITLE
Q: How to bind nested attributes with key?

### ISSUE THREAD

**Issue by 18601673727** [pupudu/window-table#27]
Given following code:

```tsx
<WindowTable
  columns={[
    { key: 'id', width: 50, title: 'ID'},
    { key: 'detail', width: 150, title: 'TAGS', Component: renderTags},
    { key: 'detail', width: 150, title: 'KEYWORDS', Component: renderKeywords},
  ]}
  data={data!.articles}
/>
```
Got following warnings:
```
Warning: Encountered two children with the same key, `detail`. 
Keys should be unique so that components maintain their identity across updates. 
Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

Tried `key: detail.tags` no luck..

Thanks!

**Comment by pupudu** [comment]
Hello there,

The reason you see an error like above is, that you are using the same key "detail" in the column config. For example, the error should go away if you rename them as "detail1" and "detail2". 

However, I just realized that this is an unnecessary constraint. So I removed that constraint and published version `0.8.10`. The error should go away if you update to that version.

Thank you for creating this issue.
