### ISSUE TITLE
ClassNames to elements

### ISSUE THREAD

**Issue by marizuccara** [pupudu/window-table#40]
Why not adding classnames to div elements, so we can access to them easily if we want add addictionaly styling?

**Comment by pupudu** [comment]
Hi @marizuccara 
That's a fair point. This is already possible by setting custom elements, although I agree that it takes a bit of effort. I think we can set the classNames by default.

**Comment by pupudu** [comment]
Hi @marizuccara 
Turns out, this was already implemented. I just published some docs as a guide on how to use the class names and prefixes.

https://window-table.netlify.com/docz-guides-styling-styling-with-class-names

Thank you for using Window Table
