### ISSUE TITLE
Warning: Cannot update a component (`WindowTable`) while rendering a different component (`AutoSizer`).

### ISSUE THREAD

**Issue by gabrielbezerra81** [pupudu/window-table#51]
Hi, thank you for this great library. I'm facing this warning and dont have any idea about the cause. Could you provide some help? Thanks.

Full warning text: 
index.js:1 Warning: Cannot update a component (`WindowTable`) while rendering a different component (`AutoSizer`). To locate the bad setState() call inside `AutoSizer`

It says this line in Measurer.tsx causes the warning:
`dispatch({ dimensions: [height, width], entity })`

**Comment by pupudu** [comment]
Sorry about the extreme delay to respond. This has been fixed in v0.13.2
