### ISSUE TITLE
Dynamic col widths

### ISSUE THREAD

**Issue by ptimson** [pupudu/window-table#60]
Hey @pupudu is there a way to use this lib with dynamic col widths or is it best to go with this approach? https://github.com/bvaughn/react-window/issues/60#issuecomment-588397239

Thanks

**Comment by pupudu** [comment]
Hey @ptimson 
If dynamic column widths is your only requirement, I suggest using jamesmfriedmans approach. That is smart and simple enough for the basic case. 

I suggest using window-table only if you want the additional features of this library as well. 

If you're looking for more options, there is also https://github.com/mckervinc/react-fluid-table which is taking a slightly different route from mine.
